// Task-authored packaging glue; the compiler, assembler, VM and CFF are upstream.
// SPDX-License-Identifier: CC0-1.0
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const esbuild = require('esbuild');
const Obfuscator = require('javascript-obfuscator');
const root = path.resolve(__dirname, '..');
process.chdir(root);
for (const dir of ['build', 'dist', 'evidence']) fs.mkdirSync(dir, { recursive: true });
const digest = text => crypto.createHash('sha256').update(text).digest('hex');
const license = '/*! KProtect upstream, GPL-3.0 (root: GPL-3.0-or-later). See licenses/KProtect-LICENSE.md and upstream/KProtect. */';
const cffOptions = {
    target: 'browser', compact: false, simplify: false,
    controlFlowFlattening: true, controlFlowFlatteningThreshold: 1,
    stringArray: false, stringArrayCallsTransform: false,
    deadCodeInjection: false, debugProtection: false,
    selfDefending: false, renameGlobals: false, renameProperties: false,
    identifierNamesGenerator: 'hexadecimal', seed: 20260908
};
(async () => {
    // Compile the exact upstream TypeScript compiler and assembler, externalizing Babel.
    await esbuild.build({ entryPoints: ['upstream/KProtect/packages/compiler/src/index.ts'],
        bundle: true, platform: 'node', format: 'cjs', packages: 'external',
        outfile: 'build/kprotect-compiler.cjs', sourcemap: true });
    const { protect } = require('../build/kprotect-compiler.cjs');
    const functions = [
        { id: 'unicodeDigest', file: 'src/unicode-digest.js', authored: 'task' },
        { id: 'numericLedger', file: 'src/numeric-ledger.js', authored: 'task' },
        { id: 'countSubstrings', file: 'upstream/KProtect/test/cases/string-substrings/code.js', authored: 'upstream-KProtect' }
    ];
    let baseline = '(function(g) {\nvar api = {};\n';
    let protectedBundle = '';
    let cffBundle = '';
    let noCffBundle = '';
    const records = [];
    for (const f of functions) {
        const source = fs.readFileSync(f.file, 'utf8');
        const data = protect(source);
        fs.writeFileSync(`build/${f.id}.bytecode.bin`, data.bytecode);
        fs.writeFileSync(`build/${f.id}.bytecode.json`, JSON.stringify({ bytecode: Array.from(data.bytecode), strings: data.strings }, null, 2) + '\n');
        const name = '__KProtect_' + f.id;
        const runtime = await esbuild.build({ entryPoints: ['upstream/KProtect/packages/vm/src/vm.ts'],
            bundle: true, platform: 'browser', format: 'iife', globalName: name,
            alias: { '@kprotect/compiler': path.join(root, 'upstream/KProtect/packages/compiler/src/constant.ts') },
            define: { __BYTECODE_ARRAY__: JSON.stringify(Array.from(data.bytecode)), __STRINGS_ARRAY__: JSON.stringify(data.strings) },
            minify: false, write: false, metafile: true, target: 'es2020' });
        const js = runtime.outputFiles[0].text;
        // No interpreter edits: only official placeholder substitution and enum resolution.
        protectedBundle += license + '\n(function(g) {\n' + js + '\n' +
            '(g.RealCasesVM || (g.RealCasesVM = {}))[' + JSON.stringify(f.id) + '] = ' + name + '.start;\n})(globalThis);\n';
        fs.writeFileSync(`evidence/${f.id}-vm-build-inputs.json`, JSON.stringify(runtime.metafile, null, 2) + '\n');
        const browserSource = `(function(g) { var module = {exports: {}};\n${source}\n;\n(g.__NAMESPACE__ || (g.__NAMESPACE__ = {}))[${JSON.stringify(f.id)}] = module.exports;\n})(globalThis);`;
        baseline += `api[${JSON.stringify(f.id)}] = (function() { var module = {exports: {}};\n${source}\nreturn module.exports; })();\n`;
        cffBundle += '/*! Generated by javascript-obfuscator 4.1.1, BSD-2-Clause; see licenses. */\n' +
            Obfuscator.obfuscate(browserSource.replaceAll('__NAMESPACE__', 'RealCasesCFF'), cffOptions).getObfuscatedCode() + '\n';
        noCffBundle += Obfuscator.obfuscate(browserSource.replaceAll('__NAMESPACE__', 'RealCasesNoCFF'), {...cffOptions, controlFlowFlattening: false}).getObfuscatedCode() + '\n';
        records.push({ ...f, sourceSha256: digest(source), bytecodeBytes: data.bytecode.length,
            bytecodeSha256: digest(data.bytecode), stringCount: data.strings.length });
    }
    baseline += 'g.RealCasesPlain = api;\n})(globalThis);\n';
    const files = { 'baseline.bundle.js': baseline, 'vm.bundle.js': protectedBundle,
        'cff.bundle.js': license + '\n' + cffBundle, 'cff-disabled.bundle.js': license + '\n' + noCffBundle };
    // Plain bundle includes one GPL upstream fixture too.
    files['baseline.bundle.js'] = license + '\n' + files['baseline.bundle.js'];
    for (const [name, text] of Object.entries(files)) fs.writeFileSync('dist/' + name, text);
    for (const name of ['selftest.js', 'index.html']) fs.copyFileSync('src/' + name, 'dist/' + name);
    fs.writeFileSync('evidence/build.json', JSON.stringify({ node: process.version,
        toolVersions: { esbuild: esbuild.version, javascriptObfuscator: Obfuscator.version },
        vmCommit: 'da4ea8a3095a14dbb7cdf3126cb9cc2e076fdf2a',
        cffCommit: '828a190cf80a86227ef77be38e99aad9838aed70', cffOptions, vmMinify: false, functions: records,
        files: Object.entries(files).map(([name, data]) => ({path:'dist/' + name, bytes:Buffer.byteLength(data), sha256:digest(data)})) }, null, 2) + '\n');
    console.log(JSON.stringify({status:'built', functions:records, files:Object.keys(files)}, null, 2));
})().catch(error => { console.error(error); process.exitCode = 1; });
